#!/bin/bash
echo "🍎 Tailscale GUI 앱 설치"
echo "========================"
echo ""
echo "아래 명령어를 터미널에서 실행하세요:"
echo ""
echo "brew install --cask tailscale"
echo ""
echo "✅ 설치 완료 후:"
echo "1. Launchpad에서 'Tailscale' 앱 클릭"
echo "2. 'Get Started' 또는 'Log in...' 클릭"
echo "3. Google 또는 Microsoft 계정으로 로그인"
echo "4. 완료!"
echo ""
echo "📱 모바일도 설치:"
echo "• iPhone: App Store에서 'Tailscale' 검색"
echo "• Android: Play Store에서 'Tailscale' 검색"
echo "• 같은 계정으로 로그인하면 자동 연결!"
